name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-24.04, windows-2022]
        os: [windows-2022]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Generate Version
        run : |
          cd Tools/VersionGenerator
          python3 -m pip install -r requirements.txt
          python3 VersionGenerator.py

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          version: "18.1.8"

      - name: Install Dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install libtinfo5
              
      - name: Build on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd Library
          premake5 gmake2
          echo $CC
          echo $CXX
          premake5 build

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '16.5'

      - name: Build on Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          cd Library
          premake5 vs2022
          premake5 build
